#!/usr/bin/env bash

APP="perceiveMe" # name of your release

BUILD_HOST="space" # host where to build the release
BUILD_USER="perceive_me" # local user at build host
BUILD_AT="/tmp/perceive_me/builds" # build directory on build host

STAGING_HOSTS="space" # staging / test hosts separated by space
STAGING_USER="perceive_me" # local user at staging hosts
TEST_AT="/tmp/perceive_me/tests" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="space" # deploy / production hosts separated by space
PRODUCTION_USER="perceive_me" # local user at deploy hosts
DELIVER_TO="/home/perceive_me/production" # deploy directory on production hosts